version: '3'

services:
    backend:
        build: .
        container_name: backend
        command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
        volumes:
            - ./static:/usr/src/app/staticfiles
        ports:
            - '8000:8000'
        networks:
            - web
    redis:
        image: redis
        container_name: redis
        ports:
            - '6379:6379'

networks:
    web:
