# Generated by Django 4.1.4 on 2022-12-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="board",
            table="BOARD",
        ),
    ]
