# Generated by Django 4.1.4 on 2022-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_board_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="update_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
